// Note -- this is a superset of all fields in the card, bank_account and bitcoint_receiver objects
module.exports = {
  'id': 'ba_18k5KBAE8iIXJx4mnWV35Rnl',
  'object': 'bank_account or card or bitcoin_receiver',
  'address_city': '',
  'address_country': '',
  'address_line1': '',
  'address_line1_check': '',
  'address_line2': '',
  'address_state': '',
  'address_zip': '',
  'address_zip_check': '',
  'brand': 'Visa',
  'country': 'US',
  'customer': '',
  'cvc_check': '',
  'dynamic_last4': '',
  'exp_month': 8,
  'exp_year': 2017,
  'funding': 'credit',
  'last4': '4242',
  'name': '',
  'tokenization_method': '',
  'account': 'acct_18epKhAE8iIXJx4m',
  'account_holder_name': 'Jane Austen',
  'account_holder_type': 'individual',
  'bank_name': 'STRIPE TEST BANK',
  'currency': 'usd',
  'default_for_currency': false,
  'fingerprint': 'rNUOheo5Mxi8lCO6',
  'routing_number': '110000000',
  'status': 'new',
  'active': false,
  'amount': 100,
  'amount_received': 0,
  'bitcoin_amount': 1757908,
  'bitcoin_amount_received': 0,
  'bitcoin_uri': 'bitcoin:test_7i9Fo4b5wXcUAuoVBFrc7nc9HDxD1?amount=0.01757908',
  'created': 1471583627,
  'description': 'Receiver for John Doe',
  'email': 'test@example.com',
  'filled': false,
  'inbound_address': 'test_7i9Fo4b5wXcUAuoVBFrc7nc9HDxD1',
  'livemode': false,
  'metadata': {},
  'refund_address': '',
  'uncaptured_funds': false,
  'used_for_payment': false
};
